spring:
  datasource:
    url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      data-source-properties:
        sslmode: require
  sql:
    init:
      mode: ALWAYS
