spring:
  datasource:
    url: "jdbc:${DATABASE_URL}"
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      data-source-properties:
        sslmode: require

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: trace
    org.springframework.core.env: trace
    com.zaxxer.hikari: debug
