spring:
  datasource:
    url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      data-source-properties:
        sslmode: require
  sql:
    init:
      mode: ALWAYS

logging:
  level:
    org.springframework.core.env: TRACE
    org.springframework.boot.context.config: TRACE
    org.springframework.boot.autoconfigure.jdbc: TRACE
    org.springframework.boot.context.properties: TRACE
